[project]
name = "weather_api"
version = "1.0.0"
description = "An API for access weather data"
dependencies = [
	"flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"